language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "luohuaruxue"  #修改name
  - git config user.email "690771820@qq.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master  #GITHUB_TOKEN 是在Travis中配置token的名称

branches:
  only:
    - code  #只监测源码分支，是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/luohuaruxue/luohuaruxue.github.io.git  #设置GH_REF，注意更改yourname
